=== Vikvillka/KYAR_1_SEM/LABA12HTML/main3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="head">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hobl" type="xs:string" />
              <xs:element name="hpopulation" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="string">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="obl" type="xs:string" />
              <xs:element name="population" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Vikvillka/KYAR_1_SEM/LABA12HTML/main3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="main3.xsd">
<head>
    <hobl>Область</hobl>
    <hpopulation>Население</hpopulation>
</head>
<string>
    <obl>Минская</obl>
    <population>2 018 281</population>
</string>
<string>
    <obl>Гродненская</obl>
    <population>1 026 816</population>
</string>
<string>
    <obl>Гомельская</obl>
    <population>1 388 512</population>
</string>
<string>
    <obl>Могилевская</obl>
    <population>1 024 751</population>
</string>
<string>
    <obl>Брестская</obl>
    <population>1 348 115</population>
</string>
<string>
    <obl>Витебская</obl>
    <population>1 135 731</population>
</string>
</table>
